### ISSUE TITLE
Possibility to keep srt langcode when playing so kodi can identify subtitle language

### ISSUE THREAD

**Issue by fabioneves** [ddurdle/GDrive-for-KODI#126]
I have multiple srt files, because I like to keep english and my mother language in the movie folder for example.

When playing, kodi will load the external SRT's, but the language can't be identified because of the srt filename, kodi will just say the lang is unknown.

I have my srt files like this, with movie title . lang code . srt:
- movie.title.en.srt
- movie.title.pt.srt

Would be good if we could keep the lang code even if the complete filename is different.

**Comment by ddurdle** [comment]
investigating

**Comment by ddurdle** [comment]
which version of kodi?

**Comment by fabioneves** [comment]
Both kodi versions work like that if you meant the title.lang_code.srt.

**Comment by ddurdle** [comment]
I can't get subtitles to load on KODI 17.  Please advise how you are able to successfully.

**Comment by fabioneves** [comment]
Ok, but this is not an issue with loading the subtitles or not, let me explain it better.

If you have the following structure:

![](https://i.imgur.com/UK3aIBP.png)
This is what kodi shows, when loading movie.title.avi, it knows the subtitle language, because of the language code (pt, fr, en) in the filename:

![](http://i.imgur.com/iNAHBXr.png)

This is what happens when the plugin try to load a movie:

![](http://i.imgur.com/nBtQ68I.png)

Notice the unknown subtitles at the bottom, as the file doesn't contain the lang code, Kodi doesn't know what's the language in SRT. This will affect languages loading automatically too, because kodi don't know if your preferred language is there.

ps: the other languages shown in that dialog are embedded in mkv, only the "Unknown" are external/srt.

**Comment by fabioneves** [comment]
Btw, I did a quick test with a clean version of Kodi 17.3, with nothing else installed besides the gdrive plugin with all it's default settings and I get the subtitles when I go to browse subtitles when playing a movie, but yeah.. I got 4 all of them Unknown :)

![](https://i.imgur.com/chSc8ap.png)

**Comment by ddurdle** [comment]
looks like player.setSubtitles() can only accept either a URL or a filename, and it deciphers the filename from that.  And since Google URLs don't have a filename in them, it displays what filename it does have, which is the file id.

If you want to leverage the filename as part of the subtitle, I'll need to either force the user to download and keep copies of the SRT files on their device or implement a streamer proxy that intercepts and reinterrupts URLs, tricking KODI into thinking it is a local file of filename movie.lang.srt.

**Comment by ddurdle** [comment]
BTW, did you know you can add the subtitles directly to the file?  In Google Drive, you can right click the video file and select Manage Caption Tracks and load the subtitles directly to the file.  The language indicator should automatically work.

**Comment by ddurdle** [comment]
I can also provide a right-click and select subtitle to load as default functionality, if you are using Google Spreadsheet method.

**Comment by fabioneves** [comment]
I didn't know about the manage caption thing of google drive, but anyway, I believe that only works for the encoded google files, I use the original file only because of DTS, etc. Also, it would be a pain to do that job manually for thousands of files.

The google spreadsheet method would also need to be done manually for each movie/tvshow, I'm trying to automate the process, which kodi already does if he recognizes the SRT language.

I wouldn't mind having them in a offline cache dir or something, that directory could be deleted everytime we start kodi or manually deleted. Having kodi to recognize the lang title is much more important for me.

I normally use english subtitles but I like to have portuguese subtitles aswell as my father is not tech savvy, kodi will load them automatically if it detects portuguese language.

Thanks for your time!

**Comment by ddurdle** [comment]
It is good to know the use case.  I also assume you playback via KODI library (using STRM)?

The closed caption tracks work on original playback.  Yes, they are normally only provided by Google with their transcoding service, but I load them even if the user plays back with original. 

It would be possible (and easier) to give the user an option to avoid loading all subtitles except the default defined language.  I'll have to look into how one sets this.  It would be possible to ignore all subtitles except the ones you would define in the settings.

So looking at a few options:
1) cache the SRT (this functionality exists already and can be toggled in cache but it need to override it to save the filename rather then the file id)
2) update the streamer class to intercept subtitle loads so that I can fake the filename (would involve no need to cache)
3) add functionality to favour certain languages

Also fair to note, caption tracks I convert to SRT and load them.  The language is correctly showing.  I don't recall if I do this in memory or if I'm caching it to the device.  Caption tracks  are not in a format understandable by KODI, so I convert them to SRT and then load them as if it was a subtitle file.  This bypasses the language issue but it may be doing so because it is implemented inline with 1).

**Comment by ddurdle** [comment]
BTW, just tested.  If you go into addon settings -> offline and checkbox offline SRT, it will cache the SRT files and show the correct languages for the subtitles.

![image](https://cloud.githubusercontent.com/assets/851508/26522566/67c296e2-42d1-11e7-937b-22796ac402d7.png)

**Comment by fabioneves** [comment]
This is awesome! It's working close to how I expected, but there's one little problem, even if I define in Kodi preferred subtitle language to Portuguese, it still loads the english srt file.

It looks like it's the addon alway load the last .srt file it downloaded, is this the behaviour?

**Comment by fabioneves** [comment]
About the options:

1. Looks like we already have it.
2. Not really needed as long we're able to identify the language
3. Favouring a language is something Kodi already does, no point duplicating functionality we already have out the box.

In Kodi 17 -> System -> Player -> Language -> Preferred subtitle language, when kodi finds srt files to the lang we specify here, it's supposed to load them automatically.

**Comment by ddurdle** [comment]
Does it list all the other subtitle tracks as choices?  If so, and those are correct with the language names, it sounds like setSubtitle might be behaving like you suggested (last call to it is the only one that matters).  In this case, will need to see if I'm able to pull the default track from KODI settings.  KODI may not be making it available for plugins to pull.  If it is available for plugins to pull, I agree with you.  No sense duplicating effort, and I should make use of it.

**Comment by ddurdle** [comment]
Looks like the language preference for subtitles is for KODI 17+.  I can't find it on KODI 16.1 that I develop on.

Also, I found this that seems to do the same.  Looks like KODI team may have introduced the same in 17.  http://forum.kodi.tv/showthread.php?tid=153783

**Comment by fabioneves** [comment]
Thanks for finding that, I've search it before and didn't find anything! I'm gonna try it now and report.

**Comment by fabioneves** [comment]
That service/script works perfectly, thanks again! Now just need scheduled update for strm/library and the setup is perfect.

Thanks a lot!
