### ISSUE TITLE
Unable to enroll account in Android TV

### ISSUE THREAD

**Issue by sporenet** [ddurdle/GDrive-for-KODI#170]
I can't get in to http://IPADDR:8011/enroll in my Android TV (Puffin browser)
It says ERR_CONNECTION_REFUSED
Is there any work-around?

**Comment by ddurdle** [comment]
For your device, as a temporary bypass, if you installed from the repository (http://dmdsoftware.net/repository.ddurdle.zip), you can right click on the plugin in the install addon from the repository and select an older version (0.8.52) which should be still appearing.  Enroll your account(s) when at 0.8.52 and then you can upgrade to 0.8.66.  Some android devices are blocking the enrollment method (which is done locally instead of using a remote connection).  I'll be adding back the old method as a [enroll account on android tv] in the next release.  But until then, this bypass would work.  You can also copy your settings.xml from the plugin directory from any other install that already has an enrolled account to bypass the need to enroll an account on your android tv.
