### ISSUE TITLE
improve slideshow for photos

### ISSUE THREAD

**Issue by firsttris** [ddurdle/GDrive-for-KODI#57]
Hello ddrudle,

very nice work, superious addon!

-Is there an option to do a slideshow without downloading ALL the pictures upfront?
Would it not be better to always download 10-15 pictures and start the slideshow while downloading. (from the cache folder)

-Always start downloading pictures to the cache folder when starting a slideshow from the addon
(I observed that the addon is only downloading pictures to cache folder the first time i start the slideshow... and it takes ages to load thousands of pictures, if i start slideshow a second time with empty cache folder nothing happens -° http://pastebin.com/WxBYRqsu )

-Delete the cache folder at some point.  

regards

**Comment by ddurdle** [comment]
KODI lacks the ability view a web url through the picture viewer.  Even when you use the KODI slideshow option (not the one I provide in the right-click menu), it tries to load the web urls I provide it as though it was files on the file system.  A case of "working as designed".

I used to kick off slideshows after the first photo, but KODI slideshow won't see subsequent downloaded files to that folder unless you invoke the slideshow call again (so it would simply rotate through 1 photo until all photos were done downloading).  I like the idea of downloading 10-15 and starting it then, and then "restarting" it every 15 photos later, but it'd repeat the first 15.  There might be some tricks around it.

The second time you start slideshow, it should start immediate, as it'll detect the files are there.  If you empty the cache, it'll redownload.  Perhaps you are invoking slideshow through KODI itself? which doesn't work right now, because it doesn't understand anything other than local files (no plugin calls, no web urls).  The right-click slideshow option I provide in the plugin I'm able to control.

**Comment by firsttris** [comment]
hello
i used right-click in an image of my google photos in the addon (context-menu) => slideshow 

-the first time it tries to download all pictures upfront
-second time i click slideshow, no matter if there are pictures in the cache folder or not - nothing happens - here is debug log (no error): http://pastebin.com/WxBYRqsu

maybe its related to my kodi version (16.X) but i can see no error in the log.
i will try kodi 15.X

thx for your help

**Comment by ddurdle** [comment]
Revamped slideshows and picture playback in v0.7.22.  Plugin no longer caches photos locally before playback.

**Comment by firsttris** [comment]
thx :+1: i will test and report back
regards
Tristan
