### ISSUE TITLE
A GDRIVE SERVER PROJECT ?

### ISSUE THREAD

**Issue by tatoomana** [ddurdle/GDrive-for-KODI#63]
Hi,

The biggest problem I encounter when I share with my friends and my family is that I have to create a new Client ID each time. In addition, installing the library each time is complicated and time consuming because I have French and English versions for movies and TV shows and it's long to operate .strm/scraping/checking each time.

Hence the idea of a GDrive Server as Emby Server but it would easier operation:
- Manage user accounts with a unique Client ID for everyone
- Managing the database of movies and series (scraping, strm, synopsys, thumbnails fanart, language version) with push update.
- Usage statistics.

Client side:
- authentication
- Recovery and updated directly in the Kodi's library.

Below, sketches of my thoughts :)
![gdrive evo](https://cloud.githubusercontent.com/assets/9001042/11319454/ba8734b0-901b-11e5-8a6f-df76c69aa47f.png)
![gdrive evo - users db](https://cloud.githubusercontent.com/assets/9001042/11319456/ce689b5e-901b-11e5-89ed-cc018305b37f.png)
![gdrive evo - library db](https://cloud.githubusercontent.com/assets/9001042/11319457/d95d7674-901b-11e5-9fe4-fa80f6b42c1a.png)

**Comment by ddurdle** [comment]
You put a lot of effort into this :)

I was thinking of something similar for purposes of sharing.  You can eliminate the need for a dedicated server by using Google App script.  You can use a user login schema for a user to authenticate with Google App script, and the Google App script will perform the OAUTH2 authentication with Drive and relay back the direct play streams (which, as you know, at this time doesn't need to be authenticated against with playback).  The library database in your second sketch could be stored as a Google spreadsheet.

Further, you can actually tap into multiple services.  For example, I store my media on both Google Drive and Amazon Cloud Drive.  By using this design, it could provide a direct playback link from either Google Drive or Amazon Cloud Drive (more choice is better no?), especially if there is an operational issue with Google Drive.

I love your ideas and the way you summarized them looks great.

I would like to share some more ideas and get an account setup for you on my domain for testing and feedback, as this moves forward.

Can you email me?  Do you already have my email? (hint, my github id @gmail :))

**Comment by Rick7C2** [comment]
This is something I would definitely love to have! Is this something that is being worked on? Any milestones?

**Comment by ddurdle** [comment]
Yes, it is.  The "server" part would be leveraged by Google Apps Script and the "library db" would be leveraged by a Google Sheet.  OAUTH2 would be managed by the Google Apps Script, but the "direct download" part is still be thought through.  Transcoding is not an issue, but the original streams is a bit more challenging.

**Comment by ddurdle** [comment]
Created a separate project for this: https://github.com/ddurdle/GoogleDrive-VideoStream

**Comment by negroISO** [comment]
Man, that's a lot of work, what ended up working for me was creating a spare e-mail account (google) or G-Suite e-mail. Like videos@domain.com or such. Then I would share out TV/Movies/Media to that account, run the G-Drive auth tool. Setup G-Drive on my first Kodi Box. Once it's setup I would then install the G-Drive plugin on all the other players, then just SFTP the settings.xml to each kodi box. So now G-Drive plugin is installed, it has a clientID and account.

Now to make it so my family doesn't have to worry about saving STRM or updating library and the such, I basically just have one machine that I do all library updates/changes to. It dumps off to a folder on a shared drive locally. Then XBMC/Openelec/LibreElec boxes all have TV/Movies/Media pointing to that shared location. On top of that, I setup SSH access to my extended familie's xbmc boxes, and just run a script at midnight that pushes everything locally over to them remotely. Then I initiate a reboot when it's done because I have "clean and update library" on startup enabled.

It maybe a rough cut, but it saves me from having to keep track of everyone.

**Comment by maximilianh75** [comment]
Hi Ddurdle,
I wanna know if you make an advance on server project and how make work the stream extractor in php
Thanks

**Comment by ddurdle** [comment]
development is underway

**Comment by ddurdle** [comment]
implememented as part of Python-GoogleDrive-VideoStream
