### ISSUE TITLE
NO PLAYING

### ISSUE THREAD

**Issue by tatoomana** [ddurdle/GDrive-for-KODI#70]
Hi ddurdle !

Suddenly, I can't launch playing from gdrive 0.7.6 or gdrive-testing 0.7.16
Tested both on Openelec 6.0 Kodi 15.2 & Windows 7 Kodi 14.2

here my log

FROM 0.7.6:
13:58:45 T:140327561193216  NOTICE: Thread LanguageInvoker start, auto delete: false
13:58:45 T:140327561193216  NOTICE: -->Python Interpreter Initialized<--
13:58:47 T:140327561193216   ERROR: gdrive: HTTP Error 500: Internal Server Error
13:58:47 T:140327561193216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/GDrive-for-KODI-master/default.py", line 1345, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
13:58:47 T:140330122905472   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B9CWy2PjJ_cEfi1KcGtkV0lURkdnVDhrZDJOZERmQVBOckJOTGtBXzdCWGYwazdZTTREZFE&filename=0B9CWy2PjJ_cEWnFubGNINnhuUDg&title=12+Monkeys+-+1x01+-+Fragmentation.mkv&content_type=video]

FROM 0.7.16:
14:04:56 T:140328686298880  NOTICE: Thread LanguageInvoker start, auto delete: false
14:04:56 T:140328686298880  NOTICE: -->Python Interpreter Initialized<--
14:04:57 T:140328199808768  NOTICE: Thread FileCache start, auto delete: false
14:04:58 T:140328686298880   ERROR: gdrive-testing: HTTP Error 500: Internal Server Error
14:04:58 T:140328686298880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive-testing/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
14:04:58 T:140330122905472   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.gdrive-testing/?mode=video&instance=gdrive1&folder=0B9CWy2PjJ_cEfnhxX0ljNFM5VWV3Y0d1QXdRRHU1Vi1BeFh2UWl4azdERVBneUlXNHdXZ1k&filename=0B9CWy2PjJ_cET1hRc19VY2VVMEU&title=12+Monkeys+-+1x13+-+Arms+of+Mine.mkv&content_type=]
14:04:58 T:140328686298880  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by negroISO** [comment]
Same here, can't play anything. Since the update. Openelec 6.0, However there's an Openelec on 5 and an older version of G-Drive that doesn't auto-update that can still play.


8:10:40 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:40 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:40 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBandvMEU1dzBlWlU&title=S01E01+-+Currahee.mkv&content_type=]
18:10:40 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:40 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:41 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:41 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:42 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBRF9McnBqNFJ1cFU&title=S01E02+-+Day+of+Days.mkv&content_type=]
18:10:42 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:42 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:43 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:43 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:43 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 2, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBNjFscmRJT3NtTjA&title=S01E03+-+Carentan.mkv&content_type=]
18:10:43 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:43 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:45 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:45 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:45 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 3, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBV0l1eEQ5WUNhdlU&title=S01E04+-+Replacements.mkv&content_type=]
18:10:45 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:45 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:47 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:47 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:48 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 4, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBTmlRX3hVYzg5cnc&title=S01E05+-+Crossroads.mkv&content_type=]
18:10:48 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:48 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:49 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:49 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:49 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 5, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBUHhFM3hSTzAwb3c&title=S01E06+-+Bastogne.mkv&content_type=]
18:10:49 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:49 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:51 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:51 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:51 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 6, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBaDlaT25DY1ZCTzA&title=S01E07+-+The+Breaking+Point.mkv&content_type=]
18:10:51 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:51 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:53 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:53 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:53 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 7, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBSmhfYXlSWHBHdjg&title=S01E08+-+The+Last+Patrol.mkv&content_type=]
18:10:53 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:53 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:55 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:55 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:55 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 8, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBTTNXTy1BMl81bkE&title=S01E09+-+Why+We+Fight.mkv&content_type=]
18:10:55 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:55 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:10:57 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:10:57 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:10:57 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 9, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBNDgtc2pROEtIMUk&title=S01E10+-+Points.mkv&content_type=]
18:17:49 T:140317739161344  NOTICE: Thread LanguageInvoker start, auto delete: false
18:17:49 T:140317739161344  NOTICE: -->Python Interpreter Initialized<--
18:17:49 T:140318705780608   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
18:17:50 T:140318120867584  NOTICE: Thread BackgroundLoader start, auto delete: false
18:17:50 T:140317739161344  NOTICE: Thread JobWorker start, auto delete: true
18:17:51 T:140318120867584  NOTICE: Thread FileCache start, auto delete: false
18:17:51 T:140318120867584  NOTICE: Thread JobWorker start, auto delete: true
18:17:52 T:140318104082176  NOTICE: Previous line repeats 2 times.
18:17:52 T:140318104082176  NOTICE: Thread FileCache start, auto delete: false
18:17:53 T:140317399176960  NOTICE: Previous line repeats 3 times.
18:17:53 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:17:53 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:17:53 T:140318104082176  NOTICE: Thread FileCache start, auto delete: false
18:17:55 T:140317399176960   ERROR: gdrive: HTTP Error 500: Internal Server Error
18:17:55 T:140317399176960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.gdrive/default.py", line 864, in <module>
                                                (mediaURLs,package) = service.getPlaybackCall(package=package.package(mediaFile,mediaFolder))
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
18:17:55 T:140318705780608   ERROR: Playlist Player: skipping unplayable item: 5, path [plugin://plugin.video.gdrive/?mode=video&instance=gdrive1&folder=0B-tXacyCqocBNUwwY05OWFpQdWM&filename=0B-tXacyCqocBUHhFM3hSTzAwb3c&title=S01E06+-+Bastogne.mkv&content_type=]
18:18:08 T:140318705780608   ERROR: Unable to activate the previous window
18:18:17 T:140317399176960  NOTICE: Thread BackgroundLoader start, auto delete: false
18:18:18 T:140318120867584   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://redirect.superrepo.org/v7/addons/plugin.video.990/icon.png
18:18:18 T:140318120867584   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://redirect.superrepo.org/v7/addons/plugin.video.cinemaxx/icon.png
18:18:20 T:140318120867584   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://redirect.superrepo.org/v7/addons/plugin.video.malabartalkies/icon.png
18:18:20 T:140316828751616  NOTICE: Thread FileCache start, auto delete: false
18:18:21 T:140318120867584   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://redirect.superrepo.org/v7/addons/plugin.video.p2psport/icon.png
18:18:23 T:140317399176960  NOTICE: Thread BackgroundLoader start, auto delete: false
18:18:30 T:140317399176960  NOTICE: Previous line repeats 3 times.
18:18:30 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:18:30 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--
18:18:30 T:140317399176960  NOTICE: Thread BackgroundLoader start, auto delete: false
18:18:32 T:140317399176960  NOTICE: Thread LanguageInvoker start, auto delete: false
18:18:32 T:140317399176960  NOTICE: -->Python Interpreter Initialized<--

**Comment by ddurdle** [comment]
Are you playing this back through STRM?

**Comment by ddurdle** [comment]
The error 500 might indicate temporary Google issue.

**Comment by negroISO** [comment]
Seems some titles work and some titles don't. I have "Never Transcode"
selected since I like the high quality.

The videos play through the google drive app on iPad/iPhone and in web
browser. I've tried removing G-drive access from approved apps and readding
it.

It's strange that in a season folder, one episode might work while others
don't.

My google drive is about 50tb, so I appreciate all your work.

**Comment by negroISO** [comment]
Do you mean, am I selecting to use the transcoded version instead of
original? I have never transcode option for viewing files so they should
all just be the native file.

This all happened yesterday, I presume that's when an update was pushed
out?


Thanks again for your work!

**Comment by ddurdle** [comment]
I meant by STRM, if you are watching from KODI TV Shows (loaded into library) or from KODI Video Addons Gdrive

**Comment by negroISO** [comment]
Kodi - video - video addons - G-drive.

Didn't know it could pull into library.

**Comment by tatoomana** [comment]
Same issue from strm and from addon.

**Comment by tatoomana** [comment]
I just test again, everything seems to be back to normal.
Thank you Dylan.

**Comment by negroISO** [comment]
Seems to be working again now for me as well. Wonder if it was a Google Drive issue instead of Plugin. Tested all 4 Openelec boxes with latest version of G-Drive.

**Comment by ddurdle** [comment]
Error 500 generally is.  I'll try to update the error logging mechanism to
capture more information around error 500 for next time the problem happens
