### ISSUE TITLE
Encfs is essentially useless

### ISSUE THREAD

**Issue by WarlaxZ** [ddurdle/GDrive-for-KODI#75]
Unless you have a mount point with your encfs file system, its pretty useless.

Ie its a google drive plugin, so I'm aiming to stream from google drive, however if I want to stream from an encrypted google drive, I'll need to mount a seperate folder on  my main os filesystem, and then mount yet another folder that is the decrypted version of it and then run from there. If I am doing that, why would I use this addon and not just use the mounted decrypted folder striaght into the library?

Sorry just a bit bummed out as I thought this plugin was my ultimate solution. Nice work anyway though it does stream well from non encrypted :)

**Comment by ddurdle** [comment]
I originally created an encryption module (not using encfs) so that I could decrypt without using a mount point but I needed to use the same code to encrypt the files to store on Google Drive.  I'd prefer to use encfs and allow users to encrypt however they please.  It's more universally accepted (been using it since 2007 to store my encrypted files in various cloud services).

The only issue encfs is that there is no open implementation that doesn't use fuse -- I've looked, can't find any library that supports decrypted encfs files without using a fuse filesystem.

I find it easy enough to mount using encfs.  Have it mounting on boot-up on several OSMC devices.  I also added support for network share mounts.  I have an always-on cubieboard on my home network, and I can simply have an encfs mount there and exploit that for accessing my encrypted content.

I don't know enough about encfs to do a reasonable job re-inventing the wheel by trying to create my own fuse-less encfs implementation.  I'm happy to tap into one if it were available.

**Comment by ddurdle** [comment]
Also to clarify, you are not mounting your Google Drive.  You create two empty folders "/encrypted" and a "/decrypted".  Then you use encfs to decrypt /encrypted to /decrypted (ENCFS6_CONFIG=/path/to/.encfs.xml encfs /encrypted /decrypted).  Then you give the path /encrypted and /decrypted to the plugin.  Now when you right-click, [treat as encfs], it uses /encrypted paired with /decrypted to display your encrypted  file and folder listing.  When you view a photo/music/video file, it will download it to /encrypted and access the /decrypted version.

**Comment by WarlaxZ** [comment]
Ah I see.  Yeah my main drama is android and thus can't have said mount point. There are android apps that do it though, and I think at least one is open source and on git hub (crypt something or other)

I'll have a proper look once im at my pc and get a link for you, may even be able to help out as this is super relevant to my interests.

Although that said, how strict are Google with content on your drive?

**Comment by ddurdle** [comment]
Good point about android.  Although android uses FUSE natively, it doesn't allow userspace access, which begs the question how encfs tools work on android.  Looks like Cryptonite patches encfs to encrypt/decrypt without actually mounting a volume.  Will look at it.

Google considers anything you own yours, unless you share and get public reports that a file is not yours.  Then I assume it is deleted (DMCAed).  Never seen reports of files being selectively deleted.  Other services like Amazon are the opposite.
